### ISSUE TITLE
Cannot build for PG16r1

### ISSUE THREAD

**Issue by JamesInform** [pgspider/sqlite_fdw#84] opened 2023-09-02 13:07 UTC
I cannot build the compoent for PG16r1.

Are you planning to update the extension any time soon?

**Comment by mkgrgis** [comment] 2023-09-02 17:23
@JamesInform , please show the main compilation problems by you opinion. How many problems there are?

**Comment by JamesInform** [comment] 2023-09-04 19:11
Hi!

<img width="675" alt="image" src="https://github.com/pgspider/sqlite_fdw/assets/38714600/8d3e890e-0bcb-4585-a646-71286d6a33dd">

**Comment by mkgrgis** [comment] 2023-09-05 03:50
@JamesInform , this is `make` stop because anybody have never try to compile against PG16r1 ;-) Please add in https://github.com/pgspider/sqlite_fdw/blob/90dad0a3ae7b8ffd129149088e094276c439ed61/Makefile#L40 in your clone and `./test.sh` How many tests will be failed? Maybe compilation will be impossible?

**Comment by mkgrgis** [comment] 2023-09-05 04:09
@JamesInform , you should also copy tests from 15.0 to your version identify directory, see https://github.com/pgspider/sqlite_fdw#tests and  my extended draft https://github.com/mkgrgis/sqlite_fdw/tree/readme-fix-and-additions#tests.

**Comment by JamesInform** [comment] 2023-09-05 06:40
Thanks. When I run `./test.sh` I get:

<img width="489" alt="image" src="https://github.com/pgspider/sqlite_fdw/assets/38714600/d5478e1e-b9da-4a1f-9e9f-3fed6d31095e">

**Comment by mkgrgis** [comment] 2023-09-05 06:49
@JamesInform , what was the method of Pg source getting in you case? `git`? ` wget ... tar.gz`? Something other? Have you tested `make check` of PostgreSQL sources itself? Please also refer my draft about testing environment https://github.com/mkgrgis/sqlite_fdw/blob/readme-fix-and-additions/TESTING.md

**Comment by JamesInform** [comment] 2023-09-06 22:41
Are you able to compile the source against PG16rc1?

**Comment by mkgrgis** [comment] 2023-09-07 04:40
@JamesInform , I don't know about pgspider team, but I haven't tried to compile the source against `PG16rc1`. Anyway this need test file copying and analyse after resolving compilation problems if there are.

**Comment by JamesInform** [comment] 2023-09-07 20:19
Maybe you can try to compile. 
It seems you are more familiar with testing and error identification than me.

**Comment by mkgrgis** [comment] 2023-09-08 05:19
> It seems you are more familiar with testing and error identification than me.

I had have no testing experience at all some month before. In C projects usually somebody are welcome for questions and experiments. This is 2 sources of my testing experience. I have no experience to adopt some FDW to a new release.

**Comment by JamesInform** [comment] 2023-09-12 20:30
Great. Thanks for informing!

**Comment by devrimgunduz** [comment] 2023-09-13 12:23
@t-kataym v16 is due tomorrow. What is the status of the patch?

Regards,  Devrim

**Comment by t-kataym** [comment] 2023-09-21 07:26
Almost is done for v16beta2. We are in progress to confirm on v16.0 and will release in the next week.

**Comment by t-kataym** [comment] 2023-09-27 09:38
We have just released new sqlite_fdw supporting PostgreSQL16.0.

**Comment by devrimgunduz** [comment] 2023-09-27 09:47
Thanks!  I can confirm that it builds cleanly.

**Comment by mkgrgis** [comment] 2023-09-28 05:01
@devrimgunduz , could you please also give some advices around of https://github.com/pgspider/sqlite_fdw/pull/80 ?

**Comment by mkgrgis** [comment] 2024-05-22 07:59
@t-kataym I think this is solved and outdated issue after [CI.yml]( https://github.com/pgspider/sqlite_fdw/blob/master/.github/workflows/CI.yml) using.

**Closed** 2024-05-22 08:54 UTC
